controller_list:
  - name: panda_arm_controller
    action_ns: execute_trajectory
    type: ExecuteTrajectory
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
      - panda_joint8
  - name: hand_controller
    action_ns: pickup
    type: Pickup
    joints:
      - panda_finger_joint1
      - panda_finger_joint2
      - panda_hand_joint
